# Generated by Django 3.1.4 on 2020-12-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='list_ids',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
