# Generated by Django 3.1.4 on 2020-12-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_summary_list_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='list_ids',
            field=models.TextField(max_length=20),
        ),
    ]
