# Generated by Django 3.1.4 on 2020-12-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201225_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='list_ids',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
